services:
  dev:
    build:
      context: .
      target: dev
      args:
        PHP_DEFAULT_VERSION: ${PHP_MIN_VERSION}
    image: php-cs-custom-fixer:${PHP_MIN_VERSION}-dev
    network_mode: bridge
    user: "${HOST_UID:?run through make or export HOST_UID}:${HOST_GID:?run through make or export HOST_GID}"
    working_dir: /app
    volumes:
      - .:/app
