services:
  test:
    build:
      context: .
      target: test
      args:
        PHP_DEFAULT_VERSION: ${PHP_VERSION:-${PHP_MIN_VERSION}}
    image: php-cs-custom-fixer:${PHP_VERSION:-${PHP_MIN_VERSION}}-test
    network_mode: none
