services:
  test:
    build:
      context: .
      target: test
      args:
        PHP_VERSION: ${PHP_VERSION:-${PHP_DEFAULT_VERSION}}
    image: php-cs-custom-fixer:${PHP_VERSION:-${PHP_DEFAULT_VERSION}}-test
    network_mode: none
